name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            openjdk-11-jdk \
            unzip \
            zip \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libreadline-dev \
            libgdbm-dev \
            libbz2-dev \
            liblzma-dev

      - name: Install Buildozer and Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cython buildozer

      - name: Initialize and build APK
        run: |
          buildozer init || true
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: bin/*.apk
