name: Build Android APK

on:
  workflow_dispatch:  # Exécution manuelle via GitHub interface

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel unzip openjdk-17-jdk wget zip expect
        pip3 install --upgrade cython buildozer

    - name: Download Android SDK cmdline-tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Create repositories.cfg
      run: |
        mkdir -p $HOME/.android
        touch $HOME/.android/repositories.cfg

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses

    - name: Install SDK packages
      run: |
        sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0"

    - name: Uninstall all Android platforms except 34
      run: |
        if [ -d "$HOME/android-sdk/platforms" ]; then
          INSTALLED=$(ls $HOME/android-sdk/platforms | grep -v "android-34" || true)
          for platform in $INSTALLED; do
            echo "❌ Désinstallation : $platform"
            sdkmanager --sdk_root=$HOME/android-sdk --uninstall "platforms;$platform"
          done
        else
          echo "Répertoire platforms inexistant, rien à désinstaller."
        fi

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
