name: Build Android APK with SDK 36

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel expect

    - name: Install Buildozer
      run: pip install --upgrade cython buildozer

    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools latest
        rm tools.zip

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Accept Android SDK Licenses
      run: |
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses

    - name: Install only Android SDK 36
      run: |
        sdkmanager --sdk_root=$HOME/android-sdk \
          "platforms;android-36" \
          "build-tools;36.0.0"

    - name: Configure buildozer to use API 36
      run: |
        sed -i 's/^android.api =.*/android.api = 36/' buildozer.spec
        sed -i 's/^android.build_tools_version =.*/android.build_tools_version = 36.0.0/' buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
