name: Build Kivy Android APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y \
            python3 python3-pip python3-setuptools git unzip \
            openjdk-17-jdk autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev

      - name: Install Buildozer + Cython
        run: |
          pip install --upgrade pip
          pip install --upgrade cython buildozer python-for-android

      - name: Create .buildozer directory
        run: |
         mkdir -p ~/.buildozer

      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build APK
        env:
          BUILDOZER_ANDROID_DEBUG: 1
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-Android-APK
          path: bin/*.apk
