app:
  name: MonApp
  package: org.monapp.budget
  version: 1.0.0
  orientation: portrait
  source: .
  entrypoint: main.py

  requirements:
    - python3
    - kivy
    - android

  android:
    permissions:
      - INTERNET
      - VIBRATE

    # Pour activer le backend clavier compatible
    features:
      - android.hardware.touchscreen

  p4a:
    # Active SDL2, requis pour clavier virtuel
    bootstrap: sdl2
    sdk_dir: /chemin/vers/android/sdk
    ndk_dir: /chemin/vers/android/ndk
    android_api: 33
    ndk_api: 21

  include_dirs:
    - .

  archs:
    - armeabi-v7a
    - arm64-v8a

  # Options facultatives de build (optimisations)
  extra_args:
    - --copy-libs
    - --force-build
