name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel unzip openjdk-17-jdk wget
        pip3 install --upgrade buildozer cython

    - name: Download Android SDK cmdline-tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip

    - name: Set ANDROID_SDK_ROOT and add tools to PATH
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Install SDK packages
      run: |
        yes | sdkmanager --sdk_root=$HOME/android-sdk --channel=3 \
          "platform-tools" "platforms;android-34" "build-tools;36.0.0"

    - name: Manually accept Android SDK licenses
      run: |
        mkdir -p $HOME/android-sdk/licenses
        echo -n "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/android-sdk/licenses/android-sdk-license
        echo -n "d56f5187479451eabf01fb78af6dfcb131a6481e" > $HOME/android-sdk/licenses/android-sdk-preview-license

    - name: Build APK with Buildozer
      run: |
        buildozer android debug
