name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          libncurses5 \
          libncurses5-dev \
          libsqlite3-dev \
          libssl-dev \
          openssl \
          python3-pip \
          unzip \
          zlib1g-dev \
          libjpeg-dev \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          openjdk-17-jdk \
          pkg-config \
          autoconf \
          libtool \
          cmake \
          automake \
          libltdl-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Accept Android Licenses and install SDK components
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools.zip -d latest
        rm commandlinetools.zip
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0"

    - name: Set environment variables
      run: echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV

    - name: Build APK with Buildozer
      run: buildozer android debug
