name: Build Kivy Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk wget
          pip install --upgrade pip
          pip install buildozer cython

      - name: Download Android SDK Command-line tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
          unzip tools.zip -d temp
          mv temp/cmdline-tools latest
          rm -rf temp tools.zip

      - name: Add SDK manager to PATH
        run: echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Accept Android SDK Licenses
        run: |
          yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses

      - name: Install Android SDK Build-Tools 36.0.0
        run: |
          sdkmanager \
            --sdk_root=${ANDROID_SDK_ROOT} \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;36.0.0"

      - name: Initialize Buildozer
        run: buildozer init

      - name: Build APK
        run: |
          buildozer android debug
