name: Build Kivy Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool \
            libffi-dev libssl-dev build-essential zip unzip \
            openjdk-11-jdk python3-pip \
            libncurses-dev libstdc++6 zlib1g-dev \
            libsqlite3-dev libjpeg-dev libfreetype6-dev \
            pkg-config libgl1-mesa-dev libgles2-mesa-dev \
            libgstreamer1.0-0 gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly gstreamer1.0-libav \
            libmtdev-dev libtiff5-dev libjpeg8-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
            libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev cmake git-core

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install Cython virtualenv
          pip install buildozer

      - name: Download and install Android SDK cmdline-tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
          unzip tools.zip -d temp
          mv temp/cmdline-tools latest
          rm -rf temp tools.zip

      - name: Set PATH for sdkmanager
        run: |
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/36.0.0" >> $GITHUB_PATH

      - name: Update sdkmanager
        run: sdkmanager --update

      - name: Accept all Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required Android packages including build-tools 36
        run: |
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;36.0.0"

      # Ne pas nettoyer les builds précédents pour éviter les erreurs liées à python-for-android
      # - name: Clean previous builds
      #   run: |
      #     rm -rf .buildozer
      #     rm -rf bin

      - name: Build the APK
        run: buildozer android debug
