name: Build Android APK

on:
  workflow_dispatch:  # Exécution manuelle via l’interface GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel unzip openjdk-17-jdk wget zip expect
        pip3 install --upgrade cython buildozer

    - name: Download Android SDK cmdline-tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Créer repositories.cfg
      run: |
        mkdir -p $HOME/.android
        touch $HOME/.android/repositories.cfg

    - name: Forcer acceptation manuelle des licences (build-tools 36)
      run: |
        mkdir -p $HOME/.android/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/.android/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $HOME/.android/licenses/android-sdk-license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> $HOME/.android/licenses/android-sdk-license
        echo "e9acab5b5fbb560a03500a0a19c8d6bba236b4b1" >> $HOME/.android/licenses/android-sdk-license

    - name: Installer Android SDK platform et build-tools 36
      run: |
        yes | sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-36" \
          "build-tools;36.0.0"

    - name: Ré-accepter les licences SDK (sécurité)
      run: yes | sdkmanager --licenses

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
