
name: Build APK

on:
  workflow_dispatch:  # Permet de déclencher manuellement
  push:
    branches:
      - main           # Déclenche quand tu pushes sur main
  create:
    tags:
      - 'v*'           # Déclenche sur création de tag v*

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:python3.10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK on release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
