name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            openjdk-11-jdk \
            unzip \
            zip \
            git \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libreadline-dev \
            libgdbm-dev \
            libbz2-dev \
            liblzma-dev

      - name: Install Android SDK
        run: |
          mkdir -p /opt/android-sdk/cmdline-tools
          cd /opt/android-sdk/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk.zip
          rm sdk.zip
        env:
          ANDROID_HOME: /opt/android-sdk
          ANDROID_SDK_ROOT: /opt/android-sdk
          PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/emulator:${{ env.PATH }}

      - name: Accept licenses & install build tools
        run: |
          yes | /opt/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          /opt/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        env:
          ANDROID_HOME: /opt/android-sdk
          ANDROID_SDK_ROOT: /opt/android-sdk
          PATH: /opt/android-sdk/cmdline-tools/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/emulator:${{ env.PATH }}

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cython buildozer

      - name: Build APK
        run: |
          buildozer android debug
        env:
          ANDROID_HOME: /opt/android-sdk
          ANDROID_SDK_ROOT: /opt/android-sdk
          PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/emulator:${{ env.PATH }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "New Kivy Build - ${{ github.run_number }}"
          tag_name: "v${{ github.run_number }}"
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
