name: Build Kivy Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential zip unzip openjdk-11-jdk \
            python3-pip libffi-dev libssl-dev \
            libgl1-mesa-dev libgles2-mesa-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libfreetype6-dev libjpeg-dev libtiff5-dev pkg-config cmake wget

      - name: Install buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer Cython

      - name: Download and extract Android SDK Command-line tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d tmp
          mv tmp/cmdline-tools latest
          rm -rf tmp

      - name: Set PATH to access sdkmanager
        run: |
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Accept licenses and install SDK packages
        run: |
          sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Clean previous builds
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Build the app
        run: buildozer android debug
