name: Build APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libzip-dev openjdk-17-jdk unzip python3-pip git zip curl \
            build-essential autoconf automake libtool pkg-config python3-dev \
            zlib1g-dev libncurses5-dev libffi-dev libsqlite3-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython virtualenv buildozer packaging appdirs six

      - name: Install Android SDK in Buildozer expected path
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip sdk-tools.zip -d cmdline-temp
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-temp/cmdline-tools/* android-sdk/cmdline-tools/latest/
          yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses
          android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      - name: Create SDK tools symlink
        run: |
          ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest $HOME/.buildozer/android/platform/android-sdk/tools

      - name: Build APK with Buildozer
        env:
          ANDROIDSDK: $HOME/.buildozer/android/platform/android-sdk
        run: buildozer android release

      - name: Debug – Check bin/
        run: ls -la bin/

      - name: Upload APK to GitHub Release (on tag only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
