name: Build Kivy Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK cmdline-tools
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk unzip curl
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip tools.zip -d latest
        rm tools.zip

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Accept licenses and install packages
      run: |
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;36.0.0"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug
