name: Build APK with python-for-android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SDK_DIR: ${{ env.HOME }}/android-sdk
      NDK_DIR: ${{ env.HOME }}/android-ndk

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip libncurses-dev libtool libtool-bin automake autoconf pkg-config m4
        python3 -m pip install --upgrade pip
        pip install cython virtualenv
        pip install git+https://github.com/kivy/python-for-android.git

    - name: Download Android SDK and NDK
      run: |
        mkdir -p "$SDK_DIR" "$NDK_DIR"
        curl -s https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
        unzip cmdline-tools.zip -d "$SDK_DIR"
        mv "$SDK_DIR/cmdline-tools" "$SDK_DIR/cmdline-tools-temp"
        mkdir -p "$SDK_DIR/cmdline-tools/latest"
        mv "$SDK_DIR/cmdline-tools-temp"/* "$SDK_DIR/cmdline-tools/latest"

        yes | "$SDK_DIR/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK_DIR" --licenses
        "$SDK_DIR/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK_DIR" \
          "platform-tools" \
          "platforms;android-36" \
          "build-tools;36.0.0" \
          "ndk;25.2.9519653"

    - name: Prepare build environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install cython

        find . -name "aclocal.m4" -delete
        find . -name "autom4te.cache" -type d -exec rm -rf {} +

    - name: Build APK
      run: |
        source venv/bin/activate
        p4a apk --private . \
          --package=org.example.monapp \
          --name="MonApp" \
          --version=0.1 \
          --bootstrap=sdl2 \
          --requirements=python3,kivy \
          --arch=armeabi-v7a,arm64-v8a \
          --sdk_dir="$SDK_DIR" \
          --ndk_dir="$NDK_DIR/ndk/25.2.9519653" \
          --android_api=36 \
          --build_dir=./build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: monapp-apk
        path: build/*.apk
