name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_SDK_ROOT: /opt/android-sdk
      PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/emulator:${{ env.PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip git python3-pip libffi-dev libssl-dev libsqlite3-dev zlib1g-dev

      - name: Install Android SDK
        run: |
          sudo mkdir -p /opt/android-sdk/cmdline-tools
          cd /opt/android-sdk/cmdline-tools
          sudo wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          sudo unzip sdk-tools.zip -d latest
          yes | sudo /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk --licenses
          sudo /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0" \
            "ndk;23.1.7779620" \
            "cmdline-tools;latest"

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install Cython buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "New APK Release"
          tag_name: "v1.${{ github.run_number }}"
          files: bin/*.apk
